"""
build_eda_notebook.py

Builds and executes docs/eda_notebook.ipynb against the v7 five-table
schema. Written as a script (not hand-authored JSON) so it can be
regenerated any time the generator changes, same pattern as v6.

Known Windows/Jupyter gotcha (hit it twice on this project):
non-ASCII characters (em dash, plus-minus) in print() output can get
corrupted to a replacement character when a Jupyter kernel subprocess
runs under Windows' default console codepage. Every string below is
plain ASCII/hyphen for that reason - verified by grepping the saved
notebook JSON for U+FFFD after execution, not just checking exit code.
"""

import nbformat as nbf
from nbclient import NotebookClient

nb = nbf.v4.new_notebook()
cells = []

def md(text):
    cells.append(nbf.v4.new_markdown_cell(text))

def code(text):
    cells.append(nbf.v4.new_code_cell(text))

md("# Resolvia EDA - v7 Five-Table Schema\n\n"
   "Break taxonomy: 4 families (routing) x 20 root causes (the real "
   "classification target - see Open Issue #1 / `check_ml_targets.py`). "
   "Data generated by `generate_trade_breaks.py`, validated by "
   "`validate_dataset.py`.")

code("""
import pandas as pd
import matplotlib.pyplot as plt

trades = pd.read_csv("../data/trades.csv")
positions = pd.read_csv("../data/positions.csv")
cash = pd.read_csv("../data/cash_transactions.csv")
settlements = pd.read_csv("../data/settlements.csv")
breaks = pd.read_csv("../data/breaks.csv")

print("trades:", trades.shape)
print("positions:", positions.shape)
print("cash_transactions:", cash.shape)
print("settlements:", settlements.shape)
print("breaks:", breaks.shape)
""")

md("## 1. Break rate and family distribution\n\n"
   "Break rate is 50% (scaled-up dataset) - deliberately "
   "inflated vs. real production reconciliation (~1-5%) to densify "
   "per-root-cause training/test examples to 150 each; see "
   "generate_trade_breaks.py's `__main__` comment. Family distribution is "
   "routing information only - not balanced by design, and not the ML "
   "target (see Section 4).")

code("""
break_rate = len(breaks) / len(trades)
print(f"Break rate: {break_rate:.1%} ({len(breaks)} of {len(trades)} trades)")

fam_counts = breaks["break_type"].value_counts()
print(fam_counts)

fig, ax = plt.subplots(figsize=(6, 4))
fam_counts.plot(kind="bar", ax=ax, color="#2b6cb0")
ax.set_title("Breaks by family")
ax.set_ylabel("count")
plt.tight_layout()
plt.show()
""")

md("**Insight:** family distribution is balanced across TRADE and "
   "POSITION (largest, 6 root causes each including both confirmation "
   "causes / the 3 CA sub-causes), then SETTLEMENT and CASH (4 each) - "
   "an exact result of stratified allocation (150/root cause by "
   "construction, see `_stratified_root_causes()`), not a deliberately "
   "modeled real-world frequency. A real reconciliation desk's break mix "
   "would need to come from actual break logs, which is flagged as "
   "future work (swap in real NSE data).")

md("## 2. Root cause distribution (the actual ML target)")

code("""
rc_counts = breaks["mismatch_type"].value_counts()
print(rc_counts)

fig, ax = plt.subplots(figsize=(8, 6))
rc_counts.sort_values().plot(kind="barh", ax=ax, color="#2f855a")
ax.set_title("Breaks by root cause (20 classes)")
ax.set_xlabel("count")
plt.tight_layout()
plt.show()
""")

md("**Insight:** with 3000 breaking trades stratified evenly across 20 "
   "root causes (150 each), per-class test-set support is now in the "
   "~30 range rather than single digits - meaningfully more statistically "
   "stable than the original 525-break generation. Model comparison "
   "still reports per-class F1, not just macro-F1, since class balance "
   "here is a generation choice, not evidence real break volume is even.")

md("## 3. Severity and corporate-action breakdown")

code("""
sev_counts = breaks["severity"].value_counts().reindex(["P0", "P1", "P2"])
print(sev_counts)

ca_counts = breaks["corporate_action_type"].fillna("").replace("", "NOT_CA").value_counts()
print(ca_counts)

fig, axes = plt.subplots(1, 2, figsize=(10, 4))
sev_counts.plot(kind="bar", ax=axes[0], color="#c53030")
axes[0].set_title("Breaks by severity")
ca_counts.plot(kind="bar", ax=axes[1], color="#805ad5")
axes[1].set_title("Corporate-action breakdown")
plt.tight_layout()
plt.show()
""")

md("**Insight:** P0 (critical/settlement-risk) breaks come from 5 of the "
   "20 root causes by design (missing booking, missing cash entry, wrong "
   "SSI, missing instruction, missing confirmation) - these are exactly "
   "the causes the payment-failure and audit-trail narrative "
   "needs to be demonstrable, not an accident of random sampling. Of the "
   "3000 breaks, the 450 corporate-action ones (3 root causes out of 20, "
   "150 each by stratified construction) split into MANDATORY and "
   "VOLUNTARY - the voluntary subset is the one that must show 100% "
   "escalation through the human-control gate, the single most important "
   "governance metric in the whole project per the original CA design.")

md("## 4. Why family is a bad ML target and root_cause isn't\n\n"
   "See `check_ml_targets.py` for the full experiment. Summary: fitting "
   "LogisticRegression / RandomForest / XGBoost on the same 15 engineered "
   "features against both targets:")

code("""
import subprocess, sys
result = subprocess.run(
    [sys.executable, "check_ml_targets.py"],
    cwd="../data", capture_output=True, text=True,
)
print(result.stdout)
if result.returncode != 0:
    print("check_ml_targets.py FAILED, returncode", result.returncode)
    print(result.stderr)
""")

md("**Insight:** break_type (family) hits a perfect 1.000 macro-F1 for "
   "both tree models - it is close to a lookup table on which table has "
   "a non-null delta, so there is nothing for Model Comparison or Model "
   "Tuning (both course requirements) to actually show. root_cause is "
   "genuinely harder (~0.93 for the same tree models, a real ~0.16 gap "
   "from LogisticRegression) - this is the target the real classifier "
   "is built around (see `docs/model_comparison.md` for exact numbers).")

md("## 5. Feature engineering preview: quantity and cash deltas by root cause\n\n"
   "A first look at whether the engineered deltas actually separate "
   "root causes visually, not just in the model's macro-F1.")

code("""
positions_idx = positions.set_index("trade_id")
breaks_pos = breaks[breaks["break_type"] == "POSITION"].copy()
breaks_pos["actual_qty"] = breaks_pos["source_record_id"].map(positions_idx["actual_quantity"])
breaks_pos["expected_qty"] = breaks_pos["source_record_id"].map(positions_idx["expected_quantity"])
breaks_pos["qty_ratio"] = breaks_pos["actual_qty"] / breaks_pos["expected_qty"]

fig, ax = plt.subplots(figsize=(8, 5))
breaks_pos.boxplot(column="qty_ratio", by="mismatch_type", ax=ax, rot=45)
ax.set_title("actual/expected quantity ratio by POSITION root cause")
plt.suptitle("")
plt.tight_layout()
plt.show()
""")

md("**Insight:** `POS_MISSING_BOOKING` sits at ratio 0.0 (fully separable "
   "from everything else). `CA_INCORRECT_ENTITLEMENT`, "
   "`CA_MANDATORY_NOT_REFLECTED` and `CA_VOLUNTARY_DECISION` cluster "
   "around the same handful of ratios (1/1.5, 1/2, 1/3 and their nearby "
   "\"incorrect\" variants) because they're built from the same "
   "{1.5, 2.0, 3.0} corporate-action ratio set - visually confirming why "
   "the classifier can't fully separate the CA sub-causes from structured "
   "features alone, and why that's the intended design, not noise.")

md("## 6. Class imbalance summary")

code("""
imbalance = breaks["mismatch_type"].value_counts()
print(f"Largest class: {imbalance.idxmax()} ({imbalance.max()} examples)")
print(f"Smallest class: {imbalance.idxmin()} ({imbalance.min()} examples)")
print(f"Ratio: {imbalance.max() / imbalance.min():.1f}x")
""")

md("**Insight:** the imbalance ratio is at or near 1.0x (root causes are "
   "stratified to exactly 150 each, not sampled) - macro-F1 is still the "
   "right metric per the original plan's reasoning (treats every class "
   "equally regardless of frequency); the near-even balance here is a "
   "generation choice for training/test statistical power, not a claim "
   "about real break-type frequency.")

nb["cells"] = cells

client = NotebookClient(nb, timeout=120, kernel_name="resolvia-venv")
client.execute()

import os
os.makedirs("../docs", exist_ok=True)
with open("../docs/eda_notebook.ipynb", "w", encoding="utf-8") as f:
    nbf.write(nb, f)

print("Notebook written and executed: docs/eda_notebook.ipynb")
